/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Classes.Eleitor;
import ConexaoBD.ConexaoSQLite;
import ConexaoBD.EleitorDAO;
import java.util.ArrayList;
import java.util.function.Consumer;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author julio
 */
public class TelaGerarPDF extends javax.swing.JInternalFrame {
    ArrayList<Eleitor> eleitores;
    
    public TelaGerarPDF() {
        initComponents();
        
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        
        DefaultTableModel dtmEleitores = (DefaultTableModel) jCadastro.getModel();
        
        EleitorDAO eleitorDAO = new EleitorDAO(conexaoSQLite);
        
        eleitores = eleitorDAO.getEleitores();
        
        Consumer<Eleitor> consumer = s -> { 
            Object[] dados = {
                              s.getId(), s.getNome(), s.getNascimento(), s.getFuncionario(),
                              s.getEmail(),s.getTelefone1(),s.getTelefone2(),
                              s.getVoto(),s.getPleito(),s.getColaborador(),
                              s.getEndereco(),s.getBairro(),s.getZona(),s.getRegiao(), s.getObservacao()};
            dtmEleitores.addRow(dados);
        }; 
        eleitores.stream().forEach(consumer);
        
        jCadastro.setModel(dtmEleitores);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCadastro = new javax.swing.JTable();

        setClosable(true);
        setTitle("Gerar PDF");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        jButton1.setText(" Gerar PDF");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jCadastro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nascimento", "Funcionário", "E-mail", "Telefone - 1", "Telefone - 2", "Voto", "Pleito", "Colaborador", "Endereço", "Bairro", "Observação", "Zona", "Região"
            }
        ));
        jScrollPane1.setViewportView(jCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


                String path="";
        JFileChooser j= new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x=j.showSaveDialog(this);
        
//        if(x==JFileChooser.APPROVE_OPTION){
//            
            path=j.getSelectedFile().getPath();
            System.out.println(path);
//        }

        Document doc = new Document ();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"\\relatorio.pdf"));
            
            doc.open();
            
            Consumer<Eleitor> consumer = s -> { 
                
                try {   
                    doc.add(new Paragraph(s.getNome()));
                    doc.add(new Paragraph("Nascimento: " + s.getNome() + "  Funcionario:" + s.getFuncionario()));
                    doc.add(new Paragraph("E-mail: " + s.getEmail()+ "  Telefone1:" + s.getTelefone1() + "  Telefone1:" +  s.getTelefone2()));
                    doc.add(new Paragraph("Voto: " + s.getVoto() + "  Pleito:" + s.getPleito()+ "  Colaborador:" + s.getColaborador()));
                    doc.add(new Paragraph("Endereço: " + s.getEndereco()));
                    doc.add(new Paragraph("Bairro: " + s.getBairro() + "  Zona:" + s.getZona()));
                    doc.add(new Paragraph("Região: " + s.getRegiao() + "  Observação:" + s.getObservacao()));
                    doc.add(new Paragraph("-----------------------------------------------------------------------------------------------"));
                } catch (DocumentException ex) {
                    Logger.getLogger(TelaGerarPDF.class.getName()).log(Level.SEVERE, null, ex);
                }
            
                
//            Object[] dados = {
//                              s.getId(), s.getNome(), s.getNascimento(), s.getFuncionario(),
//                              s.getEmail(),s.getTelefone1(),s.getTelefone2(),
//                              s.getVoto(),s.getPleito(),s.getColaborador(),
//                              s.getEndereco(),s.getBairro(),s.getZona(),s.getRegiao(), s.getObservacao()};
//            }; 
            };
            eleitores.stream().forEach(consumer);
            
            
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(TelaGerarPDF.class.getName()).log(Level.SEVERE, null, ex);
        }

        doc.close();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTable jCadastro;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
