/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.TelaConsultaEleitor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author julio
 */
public class TelaGerarPDF extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaGerarPDF
     */
    public TelaGerarPDF() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEleitores = new javax.swing.JTable();

        setClosable(true);
        setTitle("Gerar PDF");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pdf.png"))); // NOI18N
        jButton1.setText(" Gerar PDF");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblEleitores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Data de Nascimento", "Funcionário", "E-mail", "Telefone - 1", "Telefone - 2", "Voto", "Pleito", "Colaborador", "Endereço", "Bairro", "Observação", "Zona", "Região"
            }
        ));
        jScrollPane1.setViewportView(tblEleitores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(548, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String path="";
        JFileChooser j= new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x=j.showSaveDialog(this);
        
//        if(x==JFileChooser.APPROVE_OPTION){
//            
            path=j.getSelectedFile().getPath();
            System.out.println(path);
//        }

        Document doc = new Document ();
        
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(path+"\\relatorio.pdf"));
            
            doc.open();
            
            doc.add(new Paragraph("Gerando PDF em Java - metadados"));
            
            
            
           
//            tbl.addCell("Nome");
//            tbl.addCell("Data de nacimento");
//            tbl.addCell("Funcionário");
//            tbl.addCell("E-mail");
//            tbl.addCell("Telefone 1");
//            tbl.addCell("Telefone 2");
//            tbl.addCell("Voto");
//            tbl.addCell("Pleito");
//            tbl.addCell("Colaborador");
//            tbl.addCell("Endereço");
//            tbl.addCell("Bairro");
//            tbl.addCell("Observação");
//            tbl.addCell("Zona");
//            tbl.addCell("Região");
            
//            for (int i = 0; i < tblEleitores.getRowCount(); i++  ){
                
            //Adicionando Strings
//            String nome = tblEleitores.getValueAt(i, 0).toString();
//            nascimento = tblEleitores.getValueAt(i, 0).toString();
//            funcionario = tblEleitores.getValueAt(i, 0).toString();
//            email = tblEleitores.getValueAt(i, 0).toString();
//            telefone1 = tblEleitores.getValueAt(i, 0).toString();
//            telefone2 = tblEleitores.getValueAt(i, 0).toString();
//            voto = tblEleitores.getValueAt(i, 0).toString();
//            pleito = tblEleitores.getValueAt(i, 0).toString();
//            colaborador = tblEleitores.getValueAt(i, 0).toString();
//            endereco = tblEleitores.getValueAt(i, 0).toString();
//            bairro  = tblEleitores.getValueAt(i, 0).toString();
//            observacao = tblEleitores.getValueAt(i, 0).toString();
//            zona = tblEleitores.getValueAt(i, 0).toString();
//            String regiao = tblEleitores.getValueAt(i, 0).toString();

          
//              tbl.addCell(nome);
//              tbl.addCell(nascimento);
//              tbl.addCell(funcionario);
//              tbl.addCell(email);
//              tbl.addCell(telefone1);
//              tbl.addCell(telefone2);
//              tbl.addCell(voto);
//              tbl.addCell(pleito);
//              tbl.addCell(colaborador);
//              tbl.addCell(endereco);
//              tbl.addCell(bairro);
//              tbl.addCell(observacao);
//              tbl.addCell(zona);
//              tbl.addCell(regiao);
                          
//        }

     
            
            
            
            
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaGerarPDF.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(TelaGerarPDF.class.getName()).log(Level.SEVERE, null, ex);
        }

        doc.close();

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEleitores;
    // End of variables declaration//GEN-END:variables
}
